# Generated by Django 5.0.6 on 2024-05-08 01:17
from django.db import migrations


def create_default_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model("expense_categories", "ExpenseCategory")
    db_alias = schema_editor.connection.alias
    default_expense_categories = {
        "Housing": "Rent, tenant’s insurance, repairs.",
        "Groceries": "Food, bathroom, and household supplies.",
        "Personal": "Clothing, gifts for others, health-related expenses.",
        "Entertainment": "Dining out, going to the movies, music downloads, books.",
        "Miscellaneous": "Transportation, any expenses that don’t fit into the above categories.",
    }
    for category, description in default_expense_categories.items():
        ExpenseCategory.objects.using(db_alias).create(
            name=category, description=description
        )


class Migration(migrations.Migration):

    dependencies = [
        ("expense_categories", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_default_categories)]
