# Generated by Django 5.0.6 on 2024-05-08 03:05
import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expense_categories", "0002_auto_20240508_0117"),
        ("payment_methods", "0002_auto_20240508_0200"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.FloatField()),
                ("description", models.TextField(max_length=500)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_frequency",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("next_occurrence", models.DateField(blank=True, null=True)),
                ("end_of_recurrence", models.DateField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="expense_categories.expensecategory",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="payment_methods.paymentmethod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="users.user"
                    ),
                ),
            ],
        ),
    ]
